risk: 0.01
riskReward: 1.5
stopLossMax: 0.5

macd:
  fast: 12
  slow: 26
  signal: 9
trend: 200
atr: 14

liqudate-after-min: 30

snapshot-lookback-min: 120

alpaca:
  key: ""
  secret: ""
polygon:
  key: ""

stocks:
  - "ZM"
  - "UBER"
  - "TSLA"
  - "SNAP"
  - "RKT"
  - "PLUG"
  - "PLTR"
  - "NKLA"
  - "FSLY"
  - "AMD"
  - "NVDA"
  - "AAPL"
  - "FUV"
  - "FCEL"
  - "NIO"
  - "SPCE"
  - "TRIP"
  - "APPN"
  - "SQ"
  - "PYPL"
  - "SBUX"
  - "GOOG"
  - "SHOP"
