# amount of buying power that should be risked on any one trade - default 1% (0.01)
# scenario: account is 100$, the max risk any one trade should have if lost is 1$
risk: 0.01

# ratio between the reward and risk
# scenario: if risking 1$, reward should be 1.50$ - default 1.5
riskReward: 1.5

# when setting the stop loss, a minimum floor should be set if the stock is fast falling - defaults  50% (0.5)
# scenario: planning on buying a stock at 10$/share, stopLoss begins when price hits 9$,
#   stopLossMax at 50% means it will accept sells down to 8.5$
#   in the event the stock is falling so fast and it goes below 8.5$ - it will not sell and instead wait for it come back up
stopLossMax: 0.5

# when scanning for stocks to choose from, we want to target stocks with enough risk/reward to be worth trading
#   the amount of exposure is calculated from the #risk field and the stocks latest ATR value
#   this tolerance is how much it can fluctuate from an ideally risky stock - defaults to 10% (0.1)
# scenario: a stock is estimated to have an max risk and reward of 10$ and 15$ respectively, but we'd need to spend 15k$
#   that is not worth the risk, and it would be better to focus on a more risky stock
#   on the flipside, there is an extremely volatile stock that we may need to avoid because we might not be able to get
#   into and out of the stock in good time
exposure-tolerance: .10

# MACD is used to determine buying/selling indicators - default periods are 12, 26, 9
macd:
  fast: 12
  slow: 26
  signal: 9

# Trend is a long term EMA to determine upwards or downward trends in the stock - default period is 200
trend: 200

# ATR is used to determine the stopLoss/takeProfit of orders as a measure of volatility - default period is 14
atr: 14

# maximum number of minutes an order should live
#   if the trade hasn't closed naturally before this point, it will automatically cancel the order freeing that capital
liquidate-after-min: 30

# number of minutes to wait after market open before beginning to trade
# scenario: there is often large market volatility and Unreliable data during market opens that shouldn't be traded on
trade-after-open-min: 0

# number of minutes before the market closes to stop making trades, and liquidate active positions
#   all positions should close before market close to avoid margin calls
close-before-close-min: 2

# the graphs in /snapshots will look back this many periods when generating the raphs
snapshot-lookback-min: 120

# if there is an issue with the trading app - it will auto-recovery -
#   however if it recovers within this many minutes - it will assume there is a larger issue and stop the program
recover-frequency-min: 5

# this is where you can set the KEY and SECRET for your Alpaca account
#   these values can also be set by BUNNY_ALPACA.KEY and BUNNY_ALPACA.SECRET
alpaca:
  key: ""
  secret: ""