risk: 0.01
riskReward: 1.5
stopLossMax: 0.5
exposure-tolerance: .10
margin: 0.0

macd:
  fast: 12
  slow: 26
  signal: 9
trend: 200
atr: 14

liquidate-after-min: 30
trade-after-open-min: 5
close-before-close-min: 5

snapshot-lookback-min: 30

alpaca:
  key: ""
  secret: ""
polygon:
  key: ""

stocks:
  - "FSLY"
  - "FUV"
  - "RKT"
  - "TSLA"
  - "PLUG"
  - "NKLA"
  - "LUV"
  - "FCEL"
  - "ZM"
  - "PTON"
  - "SNAP"
  - "NIO"
  - "PLTR"

