decision-maker:
  stopLoss: .25 # set stop loss order if price goes below 25% of original price
  profitMax: .50 # sell order if price goes above 50% above original price

macd-calculator:
  macd: # values used to calculate macd
    12-period-ema: 12
    26-period-ema: 26
    9-period-ema: 9
  trend: # values used to calculate trend line
    trend-ema-period: 200
  period: 60 # period in seconds - can be 60(1m), 300(5m), 900(15), 3600(1h), 21600(6h), 86400(1d) or a custom value
